/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as PointsIndexRouteImport } from './routes/points/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as CleanersIndexRouteImport } from './routes/cleaners/index'
import { Route as PointsCleanerIdRouteImport } from './routes/points/$cleanerId'
import { Route as JobsNewRouteImport } from './routes/jobs/new'
import { Route as JobsJobIdRouteImport } from './routes/jobs/$jobId'
import { Route as CleanersNewRouteImport } from './routes/cleaners/new'
import { Route as CleanersCleanerIdRouteImport } from './routes/cleaners/$cleanerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const PointsIndexRoute = PointsIndexRouteImport.update({
  id: '/points/',
  path: '/points/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const CleanersIndexRoute = CleanersIndexRouteImport.update({
  id: '/cleaners/',
  path: '/cleaners/',
  getParentRoute: () => rootRouteImport,
} as any)
const PointsCleanerIdRoute = PointsCleanerIdRouteImport.update({
  id: '/points/$cleanerId',
  path: '/points/$cleanerId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsNewRoute = JobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const CleanersNewRoute = CleanersNewRouteImport.update({
  id: '/cleaners/new',
  path: '/cleaners/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CleanersCleanerIdRoute = CleanersCleanerIdRouteImport.update({
  id: '/cleaners/$cleanerId',
  path: '/cleaners/$cleanerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cleaners/$cleanerId': typeof CleanersCleanerIdRoute
  '/cleaners/new': typeof CleanersNewRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/new': typeof JobsNewRoute
  '/points/$cleanerId': typeof PointsCleanerIdRoute
  '/cleaners/': typeof CleanersIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/points/': typeof PointsIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cleaners/$cleanerId': typeof CleanersCleanerIdRoute
  '/cleaners/new': typeof CleanersNewRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/new': typeof JobsNewRoute
  '/points/$cleanerId': typeof PointsCleanerIdRoute
  '/cleaners': typeof CleanersIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/points': typeof PointsIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cleaners/$cleanerId': typeof CleanersCleanerIdRoute
  '/cleaners/new': typeof CleanersNewRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/new': typeof JobsNewRoute
  '/points/$cleanerId': typeof PointsCleanerIdRoute
  '/cleaners/': typeof CleanersIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/points/': typeof PointsIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cleaners/$cleanerId'
    | '/cleaners/new'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/points/$cleanerId'
    | '/cleaners/'
    | '/jobs/'
    | '/points/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cleaners/$cleanerId'
    | '/cleaners/new'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/points/$cleanerId'
    | '/cleaners'
    | '/jobs'
    | '/points'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/cleaners/$cleanerId'
    | '/cleaners/new'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/points/$cleanerId'
    | '/cleaners/'
    | '/jobs/'
    | '/points/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CleanersCleanerIdRoute: typeof CleanersCleanerIdRoute
  CleanersNewRoute: typeof CleanersNewRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  JobsNewRoute: typeof JobsNewRoute
  PointsCleanerIdRoute: typeof PointsCleanerIdRoute
  CleanersIndexRoute: typeof CleanersIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  PointsIndexRoute: typeof PointsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/points/': {
      id: '/points/'
      path: '/points'
      fullPath: '/points/'
      preLoaderRoute: typeof PointsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleaners/': {
      id: '/cleaners/'
      path: '/cleaners'
      fullPath: '/cleaners/'
      preLoaderRoute: typeof CleanersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/points/$cleanerId': {
      id: '/points/$cleanerId'
      path: '/points/$cleanerId'
      fullPath: '/points/$cleanerId'
      preLoaderRoute: typeof PointsCleanerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/new': {
      id: '/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof JobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleaners/new': {
      id: '/cleaners/new'
      path: '/cleaners/new'
      fullPath: '/cleaners/new'
      preLoaderRoute: typeof CleanersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleaners/$cleanerId': {
      id: '/cleaners/$cleanerId'
      path: '/cleaners/$cleanerId'
      fullPath: '/cleaners/$cleanerId'
      preLoaderRoute: typeof CleanersCleanerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CleanersCleanerIdRoute: CleanersCleanerIdRoute,
  CleanersNewRoute: CleanersNewRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  JobsNewRoute: JobsNewRoute,
  PointsCleanerIdRoute: PointsCleanerIdRoute,
  CleanersIndexRoute: CleanersIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  PointsIndexRoute: PointsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
